# Generated by Django 4.1 on 2022-08-07 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='health_status',
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='genotype',
            field=models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='vaccinecase',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_cases', to='patients.patient'),
        ),
    ]
