# Generated by Django 4.1 on 2022-08-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_health_status_patient_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='fullname',
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
